version: '2.4'
services:

  streaming-server:
    build: 
      context: .
      dockerfile: Dockerfile-server
    image: codeworksio/streaming-server
    container_name: streaming-server
    volumes:
      - ./hls:/var/lib/streaming/hls:Z
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "1935:1935"
      - "8080:8080"

  streaming-consumer-dev:
    runtime: nvidia
    build:
      context: .
      dockerfile: Dockerfile-consumer-dev
    container_name: streaming-consumer-dev
    ports:
      - 8888:8888
    volumes:
      - ./hls:/workspace/hls:Z
      - ./backend:/workspace/pose-estimation-stream

  # serveo:
  #   image: taichunmin/serveo:latest
  #   tty: true
  #   stdin_open: true
  #   # see https://serveo.net/ for more options
  #   command: autossh -M 0 -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -o StrictHostKeyChecking=no -R pose-stream:80:pose-stream:8080 serveo.net